### ISSUE TITLE
import依赖报红

### ISSUE THREAD

**Issue by zsdwhr** [simple-robot/simbot-mirai-spring-boot-demo#1]
出现问题的simbot-mirai，version是2.0.8，预先创建的listener下的类，import部分报红，集中在love.forte.simbot.annotation.*、love.forte.simbot.api.message.*

3月份clone的version是2.0.3，依赖正常

试过ctrl+左键跳转，发现报红的依赖，如love.forte.simbot.annotation.OnGroup，在依赖库里的展示是OnGroup.class，内容如下：
‘’‘
// This class file was compiled with different version of Kotlin compiler and can't be decompiled.
//
// Current compiler ABI version is 1.1.16
// File ABI version is 1.5.1
’‘’

而2.0.3的crtl+左键可以正常显示出OnGroup的代码，内容如下
‘’‘
// IntelliJ API Decompiler stub source generated from a class file
// Implementation of methods is not available

package love.forte.simbot.annotation

@kotlin.annotation.Retention @kotlin.annotation.Target @kotlin.annotation.MustBeDocumented @love.forte.simbot.annotation.Listen @love.forte.common.utils.annotation.AnnotateMapping public final annotation class OnGroup public constructor() : kotlin.Annotation {
}
’‘’

请问一下，这种情况下，我该如何解决

**Comment by zsdwhr** [comment]
2.0.3的spring-boot-starter-parent，version是2.3.5.RELEASE
2.0.8的spring-boot-starter-parent，version是2.5.0

**Comment by ForteScarlet** [comment]
如果idea版本低于2021，尝试升级到2021以上版本

因为 `v2.0.8` 之后kotlin升级到了1.5.x，而之前版本是1.4.x

**Comment by zsdwhr** [comment]
我的idea的确是2020版本，我尝试升级2021，看能否解决该问题

**Comment by ForteScarlet** [comment]
👌 如果解决自行close即可

**Comment by zsdwhr** [comment]
已解决，感谢！
